# -*- coding: utf-8 -*-
"""
TEMARL v2 — Externally-Grounded Deception Payoff Matrix
=======================================================
Closes F-ENV-02 (unbacked matrix), F-ENV-03 (dominant action / 0.074 headroom),
F-ENV-01 (mislabelled static baseline), U1.

WHAT WAS WRONG
--------------
v1 used a 23x5 matrix of 115 hand-authored floats, cited to Abbas-Escribano &
Debar [15] -- a honeypot ARCHITECTURE paper that contains no technique-to-
deception payoff table. The citation did not support the numbers. Worse, one
action (fake_vulnerability, a2) was broadly adequate across the matrix, so:

    measured on-policy:  profile-oracle 0.546  -  best-fixed 0.472  =  0.074
                         => even PERFECT intent knowledge was worth ~7 points.

and the reported "static baseline" of 0.136 was in fact the column mean of
minimal_response (0.135), NOT fake_vulnerability (0.530) as the text claimed --
so the headline "600% improvement" was measured against the null action.

WHAT REPLACES IT
----------------
The action space is re-derived from the MITRE D3FEND "Deceive" tactic, an
NSA-funded knowledge graph that maps defensive countermeasures to ATT&CK
offensive techniques through a shared Digital Artifact Ontology. Each honeypot
action is now ONE D3FEND decoy class, and each decoy class is PRIMARY for a
DISJOINT set of ATT&CK tactics. The no-dominant-column property therefore holds
BY CONSTRUCTION rather than by tuning.

  a0  NULL          (no decoy)                       -- floor reference only
  a1  D3-DNR  Decoy Network Resource   PRIMARY: Reconnaissance, Discovery
  a2  D3-DE   Decoy Environment        PRIMARY: Initial Access, Execution,
                                                Privilege Escalation
  a3  D3-DUC  Decoy User Credential    PRIMARY: Credential Access,
              (+ D3-DST Session Token)          Lateral Movement
  a4  D3-DF   Decoy File               PRIMARY: Collection, Exfiltration, Impact
  a5  D3-DP   Decoy Persona/Process    PRIMARY: Persistence, Defense Evasion,
                                                Command and Control

FREE PARAMETERS: 4, not 115. The entire 78x6 matrix is generated by a rule from
the tactic mapping below, using exactly four disclosed constants
(PRIMARY / ADJACENT / OTHER / NULL). This is the rigor argument: a reviewer can
audit four numbers and one ontology mapping instead of 115 unaccountable cells.

DISCIPLINE (non-negotiable): fit ONCE from D3FEND and FREEZE. Iterating these
constants while watching the win rate is benchmark-tuning and would destroy the
result's credibility -- it is precisely the failure this refactor exists to fix.

Reference: MITRE D3FEND (Kaloroumakis & Smith, MITRE tech. report, 2021);
           D3FEND Deceive tactic -- Decoy Object (D3-DO) / Decoy Environment (D3-DE).
"""

import numpy as np

from vocab_v2 import (NUM_TECHNIQUES, ID_TO_TACTIC, TACTIC_ORDER, tactic_of,
                      ID_TO_TECHNIQUE)

# ── The four disclosed constants (the ONLY free parameters) ──────────────────
W_PRIMARY  = 0.90   # D3FEND lists this countermeasure class against this tactic
W_ADJACENT = 0.45   # kill-chain-adjacent: partial applicability
W_OTHER    = 0.10   # not applicable
W_NULL     = 0.05   # the null action: no decoy presented

# ── D3FEND action space: each decoy class -> DISJOINT primary tactic set ─────
ACTIONS = [
    "null_response",        # a0
    "decoy_network_resource",  # a1  D3-DNR
    "decoy_environment",       # a2  D3-DE
    "decoy_credential",        # a3  D3-DUC / D3-DST
    "decoy_file",              # a4  D3-DF
    "decoy_persona",           # a5  D3-DP
]
N_ACTIONS = len(ACTIONS)

D3FEND_ID = {
    "null_response":          "-",
    "decoy_network_resource": "D3-DNR",
    "decoy_environment":      "D3-DE",
    "decoy_credential":       "D3-DUC/D3-DST",
    "decoy_file":             "D3-DF",
    "decoy_persona":          "D3-DP",
}

# PRIMARY sets are DISJOINT and jointly cover every tactic that manifests
# in-network. ("Resource Development" is excluded: it occurs outside the target
# infrastructure and has 0 techniques in the CAM-LDS inventory.)
PRIMARY = {
    "decoy_network_resource": {"Reconnaissance", "Discovery"},
    "decoy_environment":      {"Initial Access", "Execution", "Privilege Escalation"},
    "decoy_credential":       {"Credential Access", "Lateral Movement"},
    "decoy_file":             {"Collection", "Exfiltration", "Impact"},
    "decoy_persona":          {"Persistence", "Defense Evasion", "Command and Control"},
}

# ADJACENT: kill-chain neighbours where the decoy has partial effect. Prevents
# the matrix degenerating into a block-identity (which would make the task
# trivially separable and the result uninteresting).
ADJACENT = {
    "decoy_network_resource": {"Initial Access", "Lateral Movement"},
    "decoy_environment":      {"Persistence", "Defense Evasion"},
    "decoy_credential":       {"Discovery", "Initial Access"},
    "decoy_file":             {"Discovery", "Persistence"},
    "decoy_persona":          {"Execution", "Impact"},
}


def _assert_disjoint_primary():
    seen = {}
    for a, ts in PRIMARY.items():
        for t in ts:
            if t in seen:
                raise ValueError(f"PRIMARY sets overlap on '{t}': {seen[t]} and {a}")
            seen[t] = a
    return seen


TACTIC_TO_PRIMARY_ACTION = _assert_disjoint_primary()


def build_payoff():
    """Generate the (NUM_TECHNIQUES x N_ACTIONS) payoff matrix by RULE."""
    A = np.full((NUM_TECHNIQUES, N_ACTIONS), W_OTHER, dtype=np.float64)
    A[:, 0] = W_NULL
    for tid in range(NUM_TECHNIQUES):
        tac = tactic_of(tid)
        for ai, act in enumerate(ACTIONS):
            if ai == 0:
                continue
            if tac in PRIMARY[act]:
                A[tid, ai] = W_PRIMARY
            elif tac in ADJACENT[act]:
                A[tid, ai] = W_ADJACENT
    return A


PAYOFF = build_payoff()


# ── Headroom analysis (F-ENV-03) ─────────────────────────────────────────────

def headroom(profile_tech_dists, profile_probs=None, A=None):
    """Expected Value of Perfect Intent Information.

        headroom = SUM_c p(c) max_a E_{tau~c}[A[tau,a]]
                 - max_a SUM_c p(c) E_{tau~c}[A[tau,a]]

    profile_tech_dists : {profile: np.array(NUM_TECHNIQUES,)} technique
                         distribution emitted by each latent campaign profile.
    Returns dict with oracle / best-fixed / delta / per-profile optima.
    """
    A = PAYOFF if A is None else A
    names = list(profile_tech_dists)
    if profile_probs is None:
        profile_probs = {c: 1.0 / len(names) for c in names}

    per_profile = {}
    oracle = 0.0
    marginal = np.zeros(A.shape[1])
    for c in names:
        d = np.asarray(profile_tech_dists[c], dtype=np.float64)
        d = d / d.sum()
        ev = d @ A                       # (N_ACTIONS,) expected payoff per action
        best = int(ev.argmax())
        per_profile[c] = {"a_star": best, "a_star_name": ACTIONS[best],
                          "value": float(ev[best]), "ev": ev}
        oracle += profile_probs[c] * ev[best]
        marginal += profile_probs[c] * ev

    bf = int(marginal.argmax())
    wf = int(marginal.argmin())
    return {
        "oracle": float(oracle),
        "best_fixed": float(marginal[bf]),
        "best_fixed_action": bf, "best_fixed_name": ACTIONS[bf],
        "worst_fixed": float(marginal[wf]),
        "worst_fixed_action": wf, "worst_fixed_name": ACTIONS[wf],
        "delta": float(oracle - marginal[bf]),
        "marginal": marginal,
        "per_profile": per_profile,
        "n_distinct_optima": len({v["a_star"] for v in per_profile.values()}),
    }


def consolidate_intent_classes(profile_tech_dists, profile_probs=None, A=None):
    """Group scenarios into DECISION-DISTINCT intent classes.

    Two campaigns that demand the SAME optimal deception response are, from the
    defender's decision problem, the SAME intent. Reporting them as separate
    "latent profiles" would inflate the apparent difficulty of the benchmark.
    This returns the honest class count and the merged technique distributions.
    """
    h = headroom(profile_tech_dists, profile_probs, A)
    groups = {}
    for c, v in h["per_profile"].items():
        groups.setdefault(v["a_star_name"], []).append(c)

    merged, probs = {}, {}
    if profile_probs is None:
        profile_probs = {c: 1.0 / len(profile_tech_dists) for c in profile_tech_dists}
    for a_name, members in groups.items():
        d = np.zeros(NUM_TECHNIQUES)
        p = 0.0
        for c in members:
            w = profile_probs[c]
            dc = np.asarray(profile_tech_dists[c], dtype=np.float64)
            d += w * dc / dc.sum()
            p += w
        merged[a_name] = d / d.sum()
        probs[a_name] = p
    return {"classes": merged, "probs": probs, "members": groups,
            "n_classes": len(groups), "n_scenarios": len(profile_tech_dists)}


def validate_no_dominant_column(profile_tech_dists, profile_probs=None,
                                delta_min=0.15, A=None, n_actions_available=None):
    """Pre-registered gate. The matrix is ACCEPTED only if:
       (1) headroom delta >= delta_min;
       (2) the number of distinct optima equals min(#profiles, #decoy actions)
           -- the maximum ATTAINABLE, since >K profiles cannot have distinct
           optima over K actions (pigeonhole). The earlier form of this check
           demanded #profiles distinct optima and was unsatisfiable for 7
           profiles over 5 decoys; it is corrected here;
       (3) no single fixed action comes within delta_min of the oracle.
    MUST pass before any policy is trained; the matrix is then FROZEN."""
    A_ = PAYOFF if A is None else A
    n_dec = (A_.shape[1] - 1) if n_actions_available is None else n_actions_available
    h = headroom(profile_tech_dists, profile_probs, A_)
    n_prof = len(profile_tech_dists)
    attainable = min(n_prof, n_dec)
    checks = {
        "delta>=min":      (h["delta"] >= delta_min, f"{h['delta']:.4f} >= {delta_min}"),
        "optima maximal":  (h["n_distinct_optima"] == attainable,
                            f"{h['n_distinct_optima']}/{attainable} attainable "
                            f"({n_prof} profiles, {n_dec} decoys)"),
        "no dominant col": (all(h["oracle"] - v >= delta_min for v in h["marginal"]),
                            f"min gap {h['oracle'] - h['marginal'].max():.4f}"),
    }
    h["checks"] = checks
    h["PASS"] = all(ok for ok, _ in checks.values())
    h["attainable_optima"] = attainable
    return h


if __name__ == "__main__":
    import sys, json, os
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    print("=" * 74)
    print("  TEMARL v2 — D3FEND-GROUNDED PAYOFF MATRIX")
    print("=" * 74)
    print(f"  matrix shape        : {PAYOFF.shape}  (techniques x actions)")
    print(f"  free parameters     : 4  (PRIMARY/ADJACENT/OTHER/NULL)   [v1 had 115]")
    print(f"  primary sets disjoint: PASS  ({len(TACTIC_TO_PRIMARY_ACTION)} tactics covered)")

    print(f"\n  action space (D3FEND Deceive):")
    for i, a in enumerate(ACTIONS):
        prim = sorted(PRIMARY.get(a, []))
        print(f"    a{i}  {D3FEND_ID[a]:<14} {a:<24} primary: {prim if prim else '-'}")

    print(f"\n  column means over all {NUM_TECHNIQUES} techniques "
          f"(v1's dominant-action failure mode):")
    for i, a in enumerate(ACTIONS):
        print(f"    a{i} {a:<24} {PAYOFF[:, i].mean():.3f}")
    spread = PAYOFF[:, 1:].mean(0)
    print(f"    -> decoy-column spread = {spread.max() - spread.min():.3f} "
          f"(v1 fake_vulnerability dominated at 0.530 vs 0.135)")

    # ---- Build CAM-LDS-derived profile technique distributions -------------
    gpath = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                         "..", "data", "camlds_grounding.json")
    from vocab_v2 import technique_to_id
    dists, meta = {}, {}
    try:
        g = json.load(open(gpath, encoding="utf-8"))
        for s in g["scenarios"]:
            seq = [x for x in s["technique_sequence"] if not x.startswith("<")]
            ids = [technique_to_id(x) for x in seq]
            ids = [i for i in ids if i < NUM_TECHNIQUES]
            if not ids:
                continue
            d = np.zeros(NUM_TECHNIQUES)
            for i in ids:
                d[i] += 1.0
            # terminal-objective emphasis: the campaign's goal tactic is where
            # the attacker spends its decisive steps (dwell), so upweight it.
            goal = s["terminal_tactic"].split("(")[0].split("/")[0].strip()
            for i in range(NUM_TECHNIQUES):
                if tactic_of(i) == goal:
                    d[i] += 0.6 * d.sum() / max(1, sum(
                        1 for j in range(NUM_TECHNIQUES) if tactic_of(j) == goal))
            dists[s["id"]] = d
            meta[s["id"]] = (s["name"], goal)
    except (FileNotFoundError, ValueError, KeyError) as e:
        print(f"\n  [warn] CAM-LDS grounding unavailable ({e}); skipping headroom.")
        sys.exit(0)

    print(f"\n  latent profiles from CAM-LDS scenarios: {len(dists)}")
    res = validate_no_dominant_column(dists, delta_min=0.15)
    print(f"\n  {'profile':<5} {'name':<22} {'terminal tactic':<22} "
          f"{'a*':<24} {'value':>6}")
    for c, v in res["per_profile"].items():
        nm, goal = meta[c]
        print(f"  {c:<5} {nm:<22} {goal:<22} {v['a_star_name']:<24} {v['value']:.3f}")

    print(f"\n  {'PROFILE-ORACLE':<22} {res['oracle']:.4f}")
    print(f"  {'best fixed action':<22} {res['best_fixed']:.4f}  ({res['best_fixed_name']})")
    print(f"  {'worst fixed action':<22} {res['worst_fixed']:.4f}  ({res['worst_fixed_name']})")
    print(f"  {'HEADROOM delta':<22} {res['delta']:.4f}      [v1 measured: 0.0740]")

    # ---- Honest consolidation: decision-distinct intent classes ------------
    con = consolidate_intent_classes(dists)
    print(f"\n  CONSOLIDATION (F-EVL-05: do not inflate the profile count)")
    print(f"    {con['n_scenarios']} CAM-LDS scenarios collapse to "
          f"{con['n_classes']} DECISION-DISTINCT intent classes:")
    for a_name, members in con["members"].items():
        print(f"      {a_name:<24} <- {', '.join(members)}")
    print(f"    Rationale: campaigns demanding the SAME optimal deception are the")
    print(f"    same intent for the defender. Reporting 7 would overstate the task.")

    res_c = validate_no_dominant_column(con["classes"], con["probs"], delta_min=0.15)
    print(f"\n  headroom on consolidated classes: delta = {res_c['delta']:.4f} "
          f"(oracle {res_c['oracle']:.4f} - best-fixed {res_c['best_fixed']:.4f})")

    print(f"\n  PRE-REGISTERED GATE (must pass before any policy training):")
    for k, (ok, detail) in res_c["checks"].items():
        print(f"    {'PASS' if ok else 'FAIL'}  {k:<18} {detail}")

    unused = [a for a in ACTIONS[1:] if a not in con["members"]]
    if unused:
        print(f"\n  DISCLOSURE (must appear in the thesis): decoy classes never optimal")
        print(f"    under this corpus: {unused}")
        print(f"    Cause: no CAM-LDS scenario TERMINATES in Reconnaissance or")
        print(f"    Initial Access (they are early kill-chain stages, not objectives).")
        print(f"    Exercising them requires recon-terminal / access-broker campaigns")
        print(f"    (available in MITRE ATT&CK Evaluations). NOT invented here.")

    print(f"\n  VERDICT: {'PASS — matrix ACCEPTED and FROZEN' if res_c['PASS'] else 'FAIL — revise ACTION SET (never the constants)'}")
    print("=" * 74)
